name: build

on:
  push:
    branches:
    - main
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1


    - name: Setup node 12
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # tag=v2
      with:
        node-version: '12'


    - name: node_modules cache
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
      with:
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json', '*.lock') }}
        path: |
          node_modules


    - name: Install dependencies
      run: |
        yarn install

    - name: Build
      run: |
        npm run build


    - name: Run current action
      uses: ./
      with:
        githubToken: ${{ secrets.PUSH_BACK_TOKEN }}


    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && env.PUSH_BACK_TOKEN }}
      uses: remal-github-actions/push-back@3ad8fb7d2a0d4ab53ea5b1c22138d5d9869f803b # tag=v1
      with:
        githubToken: ${{ env.PUSH_BACK_TOKEN }}
        message: '[push-back] Push-back updated files during build'


    - name: Read version
      id: readVersion
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: remal-github-actions/read-nodejs-package-version@8d7a3eaec23f631af1b3853ff39a8d3a082818d4 # tag=v1

    - name: Create tag
      env:
        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.PUSH_BACK_TOKEN }}
      uses: remal-github-actions/create-tag@d38db1b542a388ea76c5c07882ef525369069cfe # tag=v1
      with:
        githubToken: ${{ env.PUSH_BACK_TOKEN }}
        tagName: 'v${{ steps.readVersion.outputs.majorVersion }}'
        forcePush: 'true'
